<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DiagnosaSeeder extends Seeder
{
    public function run()
    {
        DB::table('diagnosas')->insert([
            ['kode' => 'A00', 'diagnosa' => 'Kolera', 'created_at' => now(), 'updated_at' => now()],
            ['kode' => 'A01.0', 'diagnosa' => 'Demam Tifoid', 'created_at' => now(), 'updated_at' => now()],
            ['kode' => 'A01.4', 'diagnosa' => 'Demam Paratifoid, tidak spesifik', 'created_at' => now(), 'updated_at' => now()],
            ['kode' => 'A02', 'diagnosa' => 'Infeksi Salmonella lainnya', 'created_at' => now(), 'updated_at' => now()],
            ['kode' => 'A03.9', 'diagnosa' => 'Shigelosis tidak spesifik, Disentri basiler', 'created_at' => now(), 'updated_at' => now()],
            ['kode' => 'A04.0', 'diagnosa' => 'Enteritis akibat Escherichia coli', 'created_at' => now(), 'updated_at' => now()],
            ['kode' => 'A05.9', 'diagnosa' => 'Keracunan makanan bakteri, tidak spesifik', 'created_at' => now(), 'updated_at' => now()],
            ['kode' => 'A06.0', 'diagnosa' => 'Disentri amuba akut', 'created_at' => now(), 'updated_at' => now()],
            ['kode' => 'A07.1', 'diagnosa' => 'Giardiasis (lambliasis)', 'created_at' => now(), 'updated_at' => now()],
            ['kode' => 'A08.4', 'diagnosa' => 'Gastroenteritis virus, tidak spesifik', 'created_at' => now(), 'updated_at' => now()],
            ['kode' => 'A09', 'diagnosa' => 'Diare dan gastroenteritis asal infeksi tertentu', 'created_at' => now(), 'updated_at' => now()],
            ['kode' => 'A15.0', 'diagnosa' => 'Tuberkulosis paru dengan hasil bakteriologis dan histologis positif', 'created_at' => now(), 'updated_at' => now()],
            ['kode' => 'A16.2', 'diagnosa' => 'Tuberkulosis paru, tidak terkonfirmasi bakteriologis atau histologis', 'created_at' => now(), 'updated_at' => now()],
            ['kode' => 'A18.0', 'diagnosa' => 'Tuberkulosis tulang dan sendi', 'created_at' => now(), 'updated_at' => now()],
            ['kode' => 'A19.9', 'diagnosa' => 'Tuberkulosis milier, tidak spesifik', 'created_at' => now(), 'updated_at' => now()],
            ['kode' => 'A20.0', 'diagnosa' => 'Pes (bubonic plague)', 'created_at' => now(), 'updated_at' => now()],
            ['kode' => 'A21.9', 'diagnosa' => 'Tulang dan sendi', 'created_at' => now(), 'updated_at' => now()],
            ['kode' => 'A22.9', 'diagnosa' => 'Antraks, tidak spesifik', 'created_at' => now(), 'updated_at' => now()],
            ['kode' => 'A23.9', 'diagnosa' => 'Brusellosis, tidak spesifik', 'created_at' => now(), 'updated_at' => now()],
            ['kode' => 'A24.9', 'diagnosa' => 'Melioidosis, tidak spesifik', 'created_at' => now(), 'updated_at' => now()],
            ['kode' => 'A25.9', 'diagnosa' => 'Rat-bite fever, tidak spesifik', 'created_at' => now(), 'updated_at' => now()],
            ['kode' => 'A26.9', 'diagnosa' => 'Erysipeloid, tidak spesifik', 'created_at' => now(), 'updated_at' => now()],
            ['kode' => 'A27.9', 'diagnosa' => 'Leptospirosis, tidak spesifik', 'created_at' => now(), 'updated_at' => now()],
            ['kode' => 'A28.9', 'diagnosa' => 'Zoonosis bakteri lainnya, tidak spesifik', 'created_at' => now(), 'updated_at' => now()],
            ['kode' => 'A30.9', 'diagnosa' => 'Kusta, tidak spesifik', 'created_at' => now(), 'updated_at' => now()],
            ['kode' => 'A31.9', 'diagnosa' => 'Infeksi mikobakterium lainnya, tidak spesifik', 'created_at' => now(), 'updated_at' => now()],
            ['kode' => 'A32.9', 'diagnosa' => 'Listeriosis, tidak spesifik', 'created_at' => now(), 'updated_at' => now()],
            ['kode' => 'A33', 'diagnosa' => 'Tetanus neonatorum', 'created_at' => now(), 'updated_at' => now()],
            ['kode' => 'A34', 'diagnosa' => 'Tetanus obstetrik', 'created_at' => now(), 'updated_at' => now()],
            ['kode' => 'A35', 'diagnosa' => 'Tetanus lainnya', 'created_at' => now(), 'updated_at' => now()],
            ['kode' => 'A36.9', 'diagnosa' => 'Difteria, tidak spesifik', 'created_at' => now(), 'updated_at' => now()],
            ['kode' => 'A37.9', 'diagnosa' => 'Pertusis, tidak spesifik', 'created_at' => now(), 'updated_at' => now()],
            ['kode' => 'A38', 'diagnosa' => 'Scarlet fever', 'created_at' => now(), 'updated_at' => now()],
            ['kode' => 'A39.9', 'diagnosa' => 'Meningokoksemia, tidak spesifik', 'created_at' => now(), 'updated_at' => now()],
            ['kode' => 'A40.9', 'diagnosa' => 'Sepsis streptokokus, tidak spesifik', 'created_at' => now(), 'updated_at' => now()],
            ['kode' => 'A41.9', 'diagnosa' => 'Sepsis, tidak spesifik', 'created_at' => now(), 'updated_at' => now()],
            ['kode' => 'A42.9', 'diagnosa' => 'Aktinomikosis, tidak spesifik', 'created_at' => now(), 'updated_at' => now()],
            ['kode' => 'A43.9', 'diagnosa' => 'Nocardiosis, tidak spesifik', 'created_at' => now(), 'updated_at' => now()],
            ['kode' => 'A44.9', 'diagnosa' => 'Bartonellosis, tidak spesifik', 'created_at' => now(), 'updated_at' => now()],
            ['kode' => 'A46', 'diagnosa' => 'Erisipelas', 'created_at' => now(), 'updated_at' => now()],
            ['kode' => 'A48.1', 'diagnosa' => 'Legionellosis', 'created_at' => now(), 'updated_at' => now()],
            ['kode' => 'A49.9', 'diagnosa' => 'Infeksi bakteri, tidak spesifik', 'created_at' => now(), 'updated_at' => now()],
            ['kode' => 'A50.9', 'diagnosa' => 'Sifilis bawaan, tidak spesifik', 'created_at' => now(), 'updated_at' => now()],
            ['kode' => 'A51.9', 'diagnosa' => 'Sifilis primer, tidak spesifik', 'created_at' => now(), 'updated_at' => now()],
            ['kode' => 'A52.9', 'diagnosa' => 'Sifilis terlambat, tidak spesifik', 'created_at' => now(), 'updated_at' => now()],
            ['kode' => 'A53.9', 'diagnosa' => 'Sifilis lainnya dan tidak spesifik', 'created_at' => now(), 'updated_at' => now()],
            ['kode' => 'A54.9', 'diagnosa' => 'Infeksi gonokokus, tidak spesifik', 'created_at' => now(), 'updated_at' => now()],
            ['kode' => 'A56.9', 'diagnosa' => 'Infeksi klamidia, tidak spesifik', 'created_at' => now(), 'updated_at' => now()],
            ['kode' => 'A57', 'diagnosa' => 'Chancroid', 'created_at' => now(), 'updated_at' => now()],
            ['kode' => 'A59.9', 'diagnosa' => 'Trikomoniasis, tidak spesifik', 'created_at' => now(), 'updated_at' => now()],
            ['kode' => 'A60.9', 'diagnosa' => 'Infeksi virus herpes anogenital, tidak spesifik', 'created_at' => now(), 'updated_at' => now()],
            ['kode' => 'A63.9', 'diagnosa' => 'Infeksi menular seksual lainnya, tidak spesifik', 'created_at' => now(), 'updated_at' => now()],
            ['kode' => 'A64', 'diagnosa' => 'Infeksi menular seksual tidak spesifik', 'created_at' => now(), 'updated_at' => now()],
            ['kode' => 'A65', 'diagnosa' => 'Spiroketosis tidak menular', 'created_at' => now(), 'updated_at' => now()],
            ['kode' => 'A66.9', 'diagnosa' => 'Yaws, tidak spesifik', 'created_at' => now(), 'updated_at' => now()],
            ['kode' => 'A67.9', 'diagnosa' => 'Pinta, tidak spesifik', 'created_at' => now(), 'updated_at' => now()],
            ['kode' => 'A69.9', 'diagnosa' => 'Infeksi spiroketa lainnya, tidak spesifik', 'created_at' => now(), 'updated_at' => now()],
            ['kode' => 'B00.9', 'diagnosa' => 'Infeksi virus herpes simpleks, tidak spesifik', 'created_at' => now(), 'updated_at' => now()],
            ['kode' => 'B01.9', 'diagnosa' => 'Cacar air (varicella), tidak spesifik', 'created_at' => now(), 'updated_at' => now()],
            ['kode' => 'B02.9', 'diagnosa' => 'Herpes zoster, tidak spesifik', 'created_at' => now(), 'updated_at' => now()],
            ['kode' => 'B05.9', 'diagnosa' => 'Campak, tidak spesifik', 'created_at' => now(), 'updated_at' => now()],
            ['kode' => 'B06.9', 'diagnosa' => 'Rubella, tidak spesifik', 'created_at' => now(), 'updated_at' => now()],
            ['kode' => 'B07.9', 'diagnosa' => 'Kutil virus, tidak spesifik', 'created_at' => now(), 'updated_at' => now()],
            ['kode' => 'B08.9', 'diagnosa' => 'Infeksi virus lainnya, tidak spesifik', 'created_at' => now(), 'updated_at' => now()],
            ['kode' => 'B09', 'diagnosa' => 'Infeksi virus tidak spesifik dengan eksantema', 'created_at' => now(), 'updated_at' => now()],
            ['kode' => 'B15.9', 'diagnosa' => 'Hepatitis A akut, tidak spesifik', 'created_at' => now(), 'updated_at' => now()],
            ['kode' => 'B16.9', 'diagnosa' => 'Hepatitis B akut, tidak spesifik', 'created_at' => now(), 'updated_at' => now()],
            ['kode' => 'B17.9', 'diagnosa' => 'Hepatitis virus akut lainnya, tidak spesifik', 'created_at' => now(), 'updated_at' => now()],
            ['kode' => 'B18.9', 'diagnosa' => 'Hepatitis virus kronis, tidak spesifik', 'created_at' => now(), 'updated_at' => now()],
            ['kode' => 'B19.9', 'diagnosa' => 'Hepatitis virus, tidak spesifik', 'created_at' => now(), 'updated_at' => now()],
            ['kode' => 'B20', 'diagnosa' => 'Penyakit HIV dengan infeksi oportunistik', 'created_at' => now(), 'updated_at' => now()],
            ['kode' => 'B21', 'diagnosa' => 'Penyakit HIV dengan neoplasma', 'created_at' => now(), 'updated_at' => now()],
            ['kode' => 'B22', 'diagnosa' => 'Penyakit HIV dengan gejala lainnya', 'created_at' => now(), 'updated_at' => now()],
            ['kode' => 'B23', 'diagnosa' => 'Penyakit HIV tanpa gejala', 'created_at' => now(), 'updated_at' => now()],
            ['kode' => 'B24', 'diagnosa' => 'Infeksi virus HIV, tidak spesifik', 'created_at' => now(), 'updated_at' => now()],
            ['kode' => 'B25.9', 'diagnosa' => 'Sitomegalovirus, tidak spesifik', 'created_at' => now(), 'updated_at' => now()],
            ['kode' => 'B26.9', 'diagnosa' => 'Gondongan (mumps), tidak spesifik', 'created_at' => now(), 'updated_at' => now()],
        ]);
    }
}
